# Generated by Django 5.2.4 on 2025-07-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='defailt/news.jpg', null=True, upload_to='news/'),
        ),
    ]
