# Generated by Django 5.2.4 on 2025-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.TimeField(default=''),
        ),
    ]
